codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

ignore:
  - "tests/*"
  - "scrapers/*"
  - "custom_panel/__init__.py"
  - "custom_panel/main.py"
  - "scripts/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false