# Custom Panel Configuration File
# This file contains all configurable parameters for the custom-panel tool

# General settings
general:
  # Output directory for results
  output_dir: "results"
  # Temporary directory for intermediate files
  temp_dir: "temp"
  # Log level (DEBUG, INFO, WARNING, ERROR)
  log_level: "INFO"
  # Species for genomic queries
  species: "human"

# Data source configurations
data_sources:
  # PanelApp configurations - Source Group
  PanelApp:
    enabled: true
    source_group: true
    category: "germline"
    evidence_score: 1.0  # Base score for any gene found in this group
    normalization:
      method: "logistic"
      k: 0.35  # Steepness of curve
      x0: 5    # Midpoint (50% confidence at 5 sources)
    # PanelApp base URLs and panels to fetch
    panels:
      - name: "PanelApp_UK"
        base_url: "https://panelapp.genomicsengland.co.uk/api/v1/panels"
        panels:
          - id: 1
            name: "Childhood_solid_tumours"
          - id: 2
            name: "Adult_solid_tumours"
          - id: 3
            name: "Haematological_malignancies"
    # Evidence level scoring
    evidence_scores:
      "3": 1.0  # Green - high confidence
      "2": 0.5  # Amber - moderate confidence
      "1": 0.1  # Red - low confidence

  # In-house panels configuration - Source Group
  Inhouse_Panels:
    enabled: true
    source_group: true
    category: "germline"
    evidence_score: 1.2  # Base score for any gene found in this group
    normalization:
      method: "linear"
      max_count: 3  # Maximum count for full confidence
    panels:
      - name: "Leipzig-Cancer_v6"
        file_path: "data/Leipzig-Cancer_v6_gene-list.xlsx"
        gene_column: "genes"
        sheet_name: "Genes"  # Optional
      - name: "Dresden-Cancer_v1"
        file_path: "data/Dresden-Cancer_v1_gene-list.xlsx"
        gene_column: "genes"
        sheet_name: "genes"  # Optional
    # Veto option: Always include genes from this source regardless of score
    veto:
      enabled: true
      reason: "Inhouse Panels should remain stable and reliable for clinical use"

  # Commercial panels configuration - Source Group
  Commercial_Panels:
    enabled: true
    source_group: true
    category: "germline"
    evidence_score: 0.8  # Base score for any gene found in this group
    normalization:
      method: "logistic"
      k: 0.25  # Steepness of curve
      x0: 7    # Midpoint (50% confidence at 7 panels)
    panels:
      - name: "Myriad_myRisk"
        file_path: "data/scraped/myriad_myrisk.json"
      - name: "Blueprint_Genetics"
        file_path: "data/scraped/blueprint_genetics.json"
      - name: "Invitae_Comprehensive"
        file_path: "data/scraped/invitae_comprehensive.json"
      - name: "GeneDx_Comprehensive"
        file_path: "data/scraped/genedx_comprehensive.json"
      - name: "Fulgent_Genetics"
        file_path: "data/scraped/fulgent_genetics.json"
      - name: "Centogene"
        file_path: "data/scraped/centogene.json"
      - name: "CEGAT"
        file_path: "data/scraped/cegat.json"
      - name: "MGZ"
        file_path: "data/scraped/mgz.json"
      - name: "UChicago"
        file_path: "data/scraped/uchicago.json"
      - name: "Prevention_Genetics"
        file_path: "data/scraped/prevention_genetics.json"
      - name: "ARUP"
        file_path: "data/scraped/arup.json"
      - name: "CGL"
        file_path: "data/scraped/cgl.json"
      - name: "NeoGenomics"
        file_path: "data/scraped/neogenomics.json"
      - name: "Natera"
        file_path: "data/scraped/natera.json"

  # COSMIC database configuration - Standalone source
  COSMIC_Germline:
    enabled: true
    source_group: false  # This is a standalone source
    category: "germline"
    evidence_score: 0.9  # Base evidence score
    source_type: "cosmic_germline"
    # COSMIC Cancer Gene Census URL
    census_url: "https://cancer.sanger.ac.uk/cosmic/file_download/GRCh38/cosmic/v97/cancer_gene_census.csv"
    # Cache settings
    cache_dir: ".cache/cosmic"
    cache_expiry_days: 30
    # Germline scoring configuration
    germline_scoring:
      enabled: true
      tier_weights:
        "1": 1.0
        "2": 0.8
        "": 0.4  # Unknown/unclassified

  # ACMG incidental findings - Standalone source
  ACMG_Incidental_Findings:
    enabled: true
    source_group: false  # This is a standalone source
    category: "germline"
    evidence_score: 1.5  # Higher weight for ACMG recommendations
    # Primary source: Live URL (scraped dynamically)
    url: "https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/"
    # Fallback source: Local file (if URL scraping fails)
    file_path: "data/acmg/acmg_incidental_findings.csv"
    # Veto option: Always include genes from this source regardless of score
    veto:
      enabled: true
      reason: "ACMG recommended for reporting of incidental findings"

  # Manual curation lists - Standalone source
  Manual_Curation:
    enabled: true
    source_group: false  # This is a standalone source
    category: "germline"
    evidence_score: 1.2  # Base evidence score
    lists:
      - name: "manual_gene-list_2023"
        file_path: "data/manual/manual_gene-list.xlsx"
        gene_column: "genes"  # Default column name for text files
    # Veto option: Always include manually curated genes regardless of score
    veto:
      enabled: true
      reason: "Manually curated and reviewed by clinical experts"


  # HPO/OMIM neoplasm gene identification - Standalone source
  HPO_Neoplasm:
    enabled: true
    source_group: false  # This is a standalone source
    category: "germline"
    evidence_score: 0.7  # Base evidence score
    # OMIM genemap2.txt file configuration
    # Option 1: Provide direct URL with your personal access token (recommended)
    # Get your token from: https://omim.org/downloads
    # Example: "https://data.omim.org/downloads/YOUR_TOKEN/genemap2.txt"
    omim_genemap2_url: null  # Set this in local config or environment
    
    # Option 2: Provide local file path if you've already downloaded it
    omim_genemap2_path: "data/omim/genemap2.txt"
    
    # Cache settings for both phenotype.hpoa and genemap2 files
    cache_dir: ".cache/hpo"
    cache_expiry_days: 30
    
    # Note: The neoplasm root term HP:0002664 is automatically used

  # ClinGen gene validity - Standalone source
  ClinGen:
    enabled: true
    source_group: false  # This is a standalone source
    category: "germline"
    evidence_score: 1.2  # Base evidence score
    # Primary source: Live API (JSON endpoint)
    url: "https://search.clinicalgenome.org/api/affiliates/40023"
    # Fallback source: Local file (if API call fails)
    file_path: "data/clingen/gene_validity.tsv"
    # Classification scoring
    classification_scores:
      "Definitive": 2.0
      "Strong": 1.5
      "Moderate": 1.0
      "Limited": 0.5
      "Disputed": 0.3
      "Refuted": 0.0  # Will be filtered out

  # GenCC gene-disease associations - Standalone source
  TheGenCC:
    enabled: true
    source_group: false  # This is a standalone source
    category: "germline"
    evidence_score: 1.2  # Base evidence score
    # Primary source: Live URL (direct Excel download)
    url: "https://search.thegencc.org/download/action/submissions-export-xlsx"
    # Fallback source: Local file (if URL download fails)
    file_path: "data/gencc/submissions_export.xlsx"
    # Keywords to filter for cancer-related diseases
    filter_keywords: ["cancer", "tumor", "tumour"]
    # Classification scoring
    classification_scores:
      "Definitive": 2.0
      "Strong": 1.5
      "Moderate": 1.0
      "Supportive": 0.7
      "Limited": 0.5
      "Disputed Evidence": 0.3
      "No Known Disease Relationship": 0.0  # Will be filtered out
      "Refuted Evidence": 0.0  # Will be filtered out

# Scoring and decision logic
scoring:
  # Source group weights for pre-aggregated groups
  source_group_weights:
    PanelApp: 1.0
    Inhouse_Panels: 1.2
    Commercial_Panels: 0.8
    COSMIC_Germline: 0.9
    ACMG_Incidental_Findings: 1.5
    Manual_Curation: 1.1
    HPO_Neoplasm: 0.7
    ClinGen: 1.2
    TheGenCC: 1.2

  # Decision thresholds
  thresholds:
    # Minimum score to include in panel
    score_threshold: 2.0
    # Minimum number of sources supporting a gene
    min_sources: 1
    # Maximum evidence score (for normalization)
    max_evidence_score: 5.0

# Annotation settings
annotation:
  # Enable/disable different annotation types
  genomic_coordinates: true
  transcript_info: true
  mane_transcripts: true
  gene_descriptions: true
  
  # Coverage calculation settings (in base pairs)
  transcript_padding: 25  # Padding added to transcript coverage calculation
  gene_padding: 5000      # Padding added to gene coverage calculation
  
  # Genome assemblies to include
  assemblies:
    - "GRCh38"
    - "GRCh37"  # Optional legacy support

# API settings
apis:
  # HGNC API settings
  hgnc:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 10000

  # Ensembl API settings
  ensembl:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 5000
    transcript_batch_size: 50  # Number of genes per batch for transcript queries

  # HPO API settings
  hpo:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 5000

# Output formats
output:
  # Formats to generate
  formats:
    - "excel"    # Comprehensive Excel file
    - "csv"      # CSV for programmatic use
    - "parquet"  # Efficient binary format
    - "bed"      # BED files for genome browsers

  # BED file generation
  bed_files:
    # Generate BED file for included genes
    germline: true
    # Extend gene coordinates by this many base pairs
    padding: 0
    # Generate exon BED files
    exons:
      enabled: true
      # Types of exon BED files to generate
      canonical_transcript: true      # Exons from canonical transcripts
      mane_select_transcript: true    # Exons from MANE Select transcripts
      mane_clinical_transcript: false # Exons from MANE Plus Clinical transcripts
      # Padding around exons in base pairs
      exon_padding: 10

  # HTML report generation
  html_report:
    # Enable interactive HTML report generation
    enabled: true
    # Include summary statistics
    include_summary: true
    # Include top scoring genes section
    include_top_genes: true
    # Include interactive datatable
    include_datatable: true

  # Intermediate file output for debugging
  intermediate_files:
    # Enable intermediate file output
    enabled: true
    # Output format for intermediate files ("csv", "excel", "parquet")
    format: "excel"
    # Include raw source data
    include_raw_data: true
    # Include standardized data
    include_standardized_data: true
    # Include merged data before scoring
    include_merged_data: true
    # Include scored data before decision logic
    include_scored_data: true
    # Include annotated final data
    include_annotated_data: true
    # Compress output files
    compress: false

  # Structured logging to files
  file_logging:
    # Enable logging to files
    enabled: false
    # Log format ("json", "text")
    format: "text"
    # Include debug logs
    include_debug: true
    # Separate log files by component
    separate_by_component: true
    # Components to log separately (if separate_by_component is true)
    components:
      - "hgnc_client"
      - "ensembl_client"
      - "merger"
      - "annotator"
      - "sources"

# Quality control
quality_control:
  # Remove genes not found in HGNC
  require_hgnc_match: true
  # Remove genes without genomic coordinates
  require_coordinates: true
  # Remove duplicates based on HGNC ID
  remove_duplicates: true
  # Minimum gene size (in base pairs) to include
  min_gene_size: 1000

# Reporting
reporting:
  # Generate summary statistics
  generate_summary: true
  # Include source breakdown in reports
  include_source_breakdown: true
  # Generate plots and visualizations
  generate_plots: false

# Performance settings
performance:
  # Number of parallel workers for batch operations
  # Recommended: 2-6 for API calls (too many can overwhelm servers)
  max_workers: 4
  # Chunk size for batch processing (coordinate lookup)
  # Larger batches = fewer API calls but longer response times
  batch_size: 300
  # Enable caching of API responses for faster reruns
  enable_caching: true
  # Cache directory (relative to working directory)
  cache_dir: ".cache"
  # Cache time-to-live in seconds (default: 30 days)
  # Set to 0 to disable expiry (cache forever)
  cache_ttl: 2592000

# Directory structure for outputs
directory_structure:
  # Base structure for organized outputs
  use_structured_output: true
  # Subdirectories for different analysis stages
  subdirs:
    raw_data: "01_raw_data"
    standardized_data: "02_standardized_data"
    merged_data: "03_merged_data"
    scored_data: "04_scored_data"
    annotated_data: "05_annotated_data"
    final_output: "06_final_output"
    logs: "logs"
    cache: "cache"
  # Timestamp format for run-specific directories
  timestamp_format: "%Y%m%d_%H%M%S"

# Scrapers configuration for commercial panels
scrapers:
  # Myriad myRisk panel
  myriad_myrisk:
    enabled: true
    url: "https://myriad.com/gene-table/"
    parser_module: "parse_myriad"
    parser_class: "MyriadParser"
    output_path: "data/scraped/myriad_myrisk.json"
  
  # Blueprint Genetics panels (multiple URLs)
  blueprint_genetics:
    enabled: true
    url: "https://blueprintgenetics.com/tests/panels/hereditary-cancer/"
    subpanel_urls:
      - "https://blueprintgenetics.com/tests/panels/hematology/comprehensive-hematology-and-hereditary-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/comprehensive-hereditary-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-breast-and-gynecological-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-breast-cancer-high-risk-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-cancer-high-risk-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-colorectal-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-endocrine-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-gastrointestinal-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hematology/hereditary-leukemia-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-lung-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/hereditary-melanoma-and-skin-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-pancreatic-cancer-core-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-pancreatic-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-paraganglioma-pheochromocytoma-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-pediatric-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-renal-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/neurofibromatosis-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/tuberous-sclerosis-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/xeroderma-pigmentosum-panel/"
    parser_module: "parse_blueprint"
    parser_class: "BlueprintParser"
    output_path: "data/scraped/blueprint_genetics.json"
  
  # Centogene panels
  centogene:
    enabled: true
    url: "https://www.centoportal.com/order/new/products/analysis-method?queryType=TEST&query=Solid%20tumor"
    parser_module: "parse_centogene"
    parser_class: "CentogeneParser"
    output_path: "data/scraped/centogene.json"
  
  # Fulgent Genetics
  fulgent_genetics:
    enabled: true
    url: "https://www.fulgentgenetics.com/comprehensivecancer-full"
    parser_module: "parse_fulgent"
    parser_class: "FulgentParser"
    output_path: "data/scraped/fulgent_genetics.json"
  
  # CEGAT
  cegat:
    enabled: true
    url: "https://www.cegat.com/diagnostics/diagnostic-panels/tumor-syndromes/"
    parser_module: "parse_cegat"
    parser_class: "CegatParser"
    output_path: "data/scraped/cegat.json"
  
  # Invitae
  invitae_comprehensive:
    enabled: true
    url: "https://www.invitae.com/en/providers/test-catalog/test-01101"
    parser_module: "parse_invitae"
    parser_class: "InvitaeParser"
    output_path: "data/scraped/invitae_comprehensive.json"
  
  # MGZ
  mgz:
    enabled: true
    url: "https://www.mgz-muenchen.de/gen-panels/panel/erbliche-tumorerkrankungen-umfassende-diagnostik.html"
    parser_module: "parse_mgz"
    parser_class: "MgzParser"
    output_path: "data/scraped/mgz.json"
  
  # University of Chicago
  uchicago:
    enabled: true
    url: "https://dnatesting.uchicago.edu/tests/comprehensive-hereditary-cancer-panel"
    parser_module: "parse_uchicago"
    parser_class: "UChicagoParser"
    output_path: "data/scraped/uchicago.json"
  
  # Prevention Genetics
  prevention_genetics:
    enabled: true
    url: "https://www.preventiongenetics.com/testInfo?val=Cancer-Panel"
    parser_module: "parse_prevention"
    parser_class: "PreventionParser"
    output_path: "data/scraped/prevention_genetics.json"
  
  # GeneDx
  genedx_comprehensive:
    enabled: true
    url: "https://www.genedx.com/tests/detail/oncogenedx-custom-panel-871"
    parser_module: "parse_genedx"
    parser_class: "GenedxParser"
    output_path: "data/scraped/genedx_comprehensive.json"
  
  # ARUP Laboratories
  arup:
    enabled: true
    url: "https://arupconsult.com/ati/hereditary-cancer-panel"
    parser_module: "parse_arup"
    parser_class: "ArupParser"
    output_path: "data/scraped/arup.json"
  
  # CGL (Cancer Genetics Lab)
  cgl:
    enabled: true
    url: "http://cancergeneticslab.ca/genes/hereditary-cancer-panel/"
    parser_module: "parse_cgl"
    parser_class: "CglParser"
    output_path: "data/scraped/cgl.json"
  
  # NeoGenomics
  neogenomics:
    enabled: true
    url: "https://neogenomics.com/test-menu/full-comprehensive-cancer-panel-germline"
    parser_module: "parse_neogenomics"
    parser_class: "NeogenomicsParser"
    output_path: "data/scraped/neogenomics.json"
  
  # Natera
  natera:
    enabled: true
    url: "https://www.natera.com/oncology/empower-hereditary-cancer-test/clinicians/"
    parser_module: "parse_natera"
    parser_class: "NateraParser"
    output_path: "data/scraped/natera.json"