# Custom Panel Configuration File
# This file contains all configurable parameters for the custom-panel tool

# General settings
general:
  # Output directory for results
  output_dir: "results"
  # Temporary directory for intermediate files
  temp_dir: "temp"
  # Log level (DEBUG, INFO, WARNING, ERROR)
  log_level: "INFO"
  # Species for genomic queries
  species: "human"

# Data source configurations
data_sources:
  # PanelApp configurations
  panelapp:
    enabled: true
    # PanelApp base URLs and panels to fetch
    panels:
      - name: "PanelApp_UK"
        base_url: "https://panelapp.genomicsengland.co.uk/api/v1/panels"
        panels:
          - id: 1
            name: "Childhood_solid_tumours"
          - id: 2
            name: "Adult_solid_tumours"
          - id: 3
            name: "Haematological_malignancies"
    # Evidence level scoring
    evidence_scores:
      "Green": 1.0
      "Amber": 0.5
      "Red": 0.1

  # In-house panels configuration
  inhouse_panels:
    enabled: true
    panels:
      - name: "Leipzig-Cancer_v6"
        file_path: "data/Leipzig-Cancer_v6_gene-list.xlsx"
        gene_column: "Gene_Symbol"
        sheet_name: "Sheet1"  # Optional
        evidence_score: 1.0
      - name: "Custom_Cardio_Panel"
        file_path: "data/cardio_genes.csv"
        gene_column: "genes"
        evidence_score: 0.9

  # Commercial panels configuration
  commercial_panels:
    enabled: true
    panels:
      - name: "Illumina_TruSight_Cancer"
        file_path: "data/commercial/illumina_trusight_cancer.pdf"
        parser_type: "pdf"
        evidence_score: 0.8
      - name: "Agilent_SureSelect"
        file_path: "data/commercial/agilent_sureselect.xlsx"
        parser_type: "excel"
        gene_column: "Gene Symbol"
        evidence_score: 0.7

  # COSMIC database configuration
  cosmic:
    enabled: true
    # COSMIC gene census file path
    file_path: "data/cosmic/cosmic_gene_census.csv"
    # Minimum number of samples to include gene
    min_samples: 5
    evidence_score: 0.9

  # ACMG incidental findings
  acmg_incidental:
    enabled: true
    # ACMG recommended genes list
    file_path: "data/acmg/acmg_incidental_findings.txt"
    evidence_score: 1.5  # Higher weight for ACMG recommendations

  # Manual curation lists
  manual_curation:
    enabled: true
    lists:
      - name: "Literature_Review_2024"
        file_path: "data/manual/literature_genes_2024.txt"
        gene_column: "gene_symbol"  # Default column name for text files
        evidence_score: 1.2
      - name: "Expert_Panel_Recommendations"
        file_path: "data/manual/expert_panel_genes.csv"
        gene_column: "Gene"
        evidence_score: 1.1
      - name: "Clinical_Variant_Database"
        file_path: "data/manual/clinical_variants.xlsx"
        gene_column: "Gene Symbol"
        evidence_score: 1.0

  # HPO/OMIM neoplasm gene identification
  hpo_neoplasm:
    enabled: true
    # Automatically search for neoplasm-related HPO terms
    use_neoplasm_search: true
    # Specific HPO terms to include (in addition to neoplasm search)
    specific_hpo_terms:
      - "HP:0002664"  # Neoplasm
      - "HP:0030358"  # Non-small cell lung carcinoma
      - "HP:0002860"  # Squamous cell carcinoma
    # Optional OMIM file for additional gene-disease associations
    omim_file_path: "data/hpo/omim_neoplasm_genes.csv"
    omim_gene_column: "Gene Symbol"
    omim_disease_column: "Disease"
    omim_id_column: "OMIM ID"
    # Scoring parameters
    base_evidence_score: 0.6
    # Maximum depth to traverse HPO hierarchy
    max_hierarchy_depth: 5

# Scoring and decision logic
scoring:
  # Category weights for different types of evidence
  category_weights:
    germline:
      panelapp: 1.0
      inhouse_panels: 1.2
      commercial_panels: 0.8
      cosmic: 0.9
      acmg_incidental: 1.5
      manual_curation: 1.1
      hpo_neoplasm: 0.7
    somatic:
      panelapp: 0.8
      inhouse_panels: 1.0
      commercial_panels: 0.9
      cosmic: 1.2
      acmg_incidental: 0.5
      manual_curation: 1.0
      hpo_neoplasm: 0.9

  # Decision thresholds
  thresholds:
    # Minimum score to include in germline panel
    germline_threshold: 2.0
    # Minimum score to include in somatic panel
    somatic_threshold: 1.5
    # Minimum number of sources supporting a gene
    min_sources: 1
    # Maximum evidence score (for normalization)
    max_evidence_score: 5.0

# Annotation settings
annotation:
  # Enable/disable different annotation types
  genomic_coordinates: true
  transcript_info: true
  mane_transcripts: true
  gene_descriptions: true
  
  # Genome assemblies to include
  assemblies:
    - "GRCh38"
    - "GRCh37"  # Optional legacy support

# API settings
apis:
  # HGNC API settings
  hgnc:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 10000

  # Ensembl API settings
  ensembl:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 5000

  # HPO API settings
  hpo:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 5000

# Output formats
output:
  # Formats to generate
  formats:
    - "excel"    # Comprehensive Excel file
    - "csv"      # CSV for programmatic use
    - "parquet"  # Efficient binary format
    - "bed"      # BED files for genome browsers

  # BED file generation
  bed_files:
    # Generate separate BED files for different categories
    germline: true
    somatic: true
    combined: true
    # Extend gene coordinates by this many base pairs
    padding: 0

# Quality control
quality_control:
  # Remove genes not found in HGNC
  require_hgnc_match: true
  # Remove genes without genomic coordinates
  require_coordinates: true
  # Remove duplicates based on HGNC ID
  remove_duplicates: true
  # Minimum gene size (in base pairs) to include
  min_gene_size: 1000

# Reporting
reporting:
  # Generate summary statistics
  generate_summary: true
  # Include source breakdown in reports
  include_source_breakdown: true
  # Generate plots and visualizations
  generate_plots: false

# Performance settings
performance:
  # Number of parallel requests for batch operations
  max_workers: 4
  # Chunk size for batch processing
  batch_size: 100
  # Enable caching of API responses
  enable_caching: true
  # Cache directory
  cache_dir: ".cache"