# Custom Panel Configuration File
# This file contains all configurable parameters for the custom-panel tool

# General settings
general:
  # Output directory for results
  output_dir: "results"
  # Temporary directory for intermediate files
  temp_dir: "temp"
  # Log level (DEBUG, INFO, WARNING, ERROR)
  log_level: "INFO"
  # Species for genomic queries
  species: "human"

# Data source configurations
data_sources:
  # PanelApp configurations
  panelapp:
    enabled: true
    # PanelApp base URLs and panels to fetch
    panels:
      - name: "PanelApp_UK"
        base_url: "https://panelapp.genomicsengland.co.uk/api/v1/panels"
        panels:
          - id: 1
            name: "Childhood_solid_tumours"
          - id: 2
            name: "Adult_solid_tumours"
          - id: 3
            name: "Haematological_malignancies"
    # Evidence level scoring
    evidence_scores:
      "3": 1.0  # Green - high confidence
      "2": 0.5  # Amber - moderate confidence
      "1": 0.1  # Red - low confidence

  # In-house panels configuration
  inhouse_panels:
    enabled: true
    panels:
      - name: "Leipzig-Cancer_v6"
        file_path: "data/Leipzig-Cancer_v6_gene-list.xlsx"
        gene_column: "genes"
        sheet_name: "Genes"  # Optional
        evidence_score: 1.0
        category: "germline"  # "germline" or "somatic"
      - name: "Dresden-Cancer_v1"
        file_path: "data/Dresden-Cancer_v1_gene-list.xlsx"
        gene_column: "genes"
        sheet_name: "genes"  # Optional
        evidence_score: 1.0
        category: "germline"  # "germline" or "somatic"

  # Commercial panels configuration - now points to JSON files generated by scrapers
  commercial_panels:
    enabled: true
    panels:
      - name: "Myriad_myRisk"
        file_path: "data/scraped/myriad_myrisk.json"
        evidence_score: 0.8
        category: "germline"  # "germline" or "somatic"
      - name: "Blueprint_Genetics"
        file_path: "data/scraped/blueprint_genetics.json"
        evidence_score: 0.8
        category: "germline"  # "germline" or "somatic"
      - name: "Invitae_Comprehensive"
        file_path: "data/scraped/invitae_comprehensive.json"
        evidence_score: 0.8
        category: "germline"  # "germline" or "somatic"
      - name: "GeneDx_Comprehensive"
        file_path: "data/scraped/genedx_comprehensive.json"
        evidence_score: 0.8
        category: "germline"  # "germline" or "somatic"
      - name: "Fulgent_Genetics"
        file_path: "data/scraped/fulgent_genetics.json"
        evidence_score: 0.7
        category: "germline"  # "germline" or "somatic"

  # COSMIC database configuration - germline only
  cosmic_germline:
    enabled: true
    source_type: "cosmic_germline"
    # COSMIC Cancer Gene Census URL
    census_url: "https://cancer.sanger.ac.uk/cosmic/file_download/GRCh38/cosmic/v97/cancer_gene_census.csv"
    # Cache settings
    cache_dir: ".cache/cosmic"
    cache_expiry_days: 30
    # Germline scoring configuration
    germline_scoring:
      enabled: true
      tier_weights:
        "1": 1.0
        "2": 0.8
        "": 0.4  # Unknown/unclassified

  # ACMG incidental findings
  acmg_incidental:
    enabled: true
    # Primary source: Live URL (scraped dynamically)
    url: "https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/"
    # Fallback source: Local file (if URL scraping fails)
    file_path: "data/acmg/acmg_incidental_findings.csv"
    evidence_score: 1.5  # Higher weight for ACMG recommendations

  # Manual curation lists
  manual_curation:
    enabled: true
    lists:
      - name: "manual_gene-list_2023"
        file_path: "data/manual/manual_gene-list.xlsx"
        gene_column: "genes"  # Default column name for text files
        evidence_score: 1.2
        category: "germline"  # "germline" or "somatic"


  # HPO/OMIM neoplasm gene identification
  hpo_neoplasm:
    enabled: true
    # OMIM genemap2.txt file configuration
    # Option 1: Provide direct URL with your personal access token (recommended)
    # Get your token from: https://omim.org/downloads
    # Example: "https://data.omim.org/downloads/YOUR_TOKEN/genemap2.txt"
    omim_genemap2_url: null  # Set this in local config or environment
    
    # Option 2: Provide local file path if you've already downloaded it
    omim_genemap2_path: "data/omim/genemap2.txt"
    
    # Cache settings for both phenotype.hpoa and genemap2 files
    cache_dir: ".cache/hpo"
    cache_expiry_days: 30
    
    # Scoring parameters
    base_evidence_score: 0.7
    # Note: The neoplasm root term HP:0002664 is automatically used

# Scoring and decision logic
scoring:
  # Category weights for different types of evidence
  category_weights:
    germline:
      panelapp: 1.0
      inhouse_panels: 1.2
      commercial_panels: 0.8
      cosmic: 0.9
      acmg_incidental: 1.5
      manual_curation: 1.1
      hpo_neoplasm: 0.7

  # Decision thresholds
  thresholds:
    # Minimum score to include in panel
    score_threshold: 2.0
    # Minimum number of sources supporting a gene
    min_sources: 1
    # Maximum evidence score (for normalization)
    max_evidence_score: 5.0

# Annotation settings
annotation:
  # Enable/disable different annotation types
  genomic_coordinates: true
  transcript_info: true
  mane_transcripts: true
  gene_descriptions: true
  
  # Genome assemblies to include
  assemblies:
    - "GRCh38"
    - "GRCh37"  # Optional legacy support

# API settings
apis:
  # HGNC API settings
  hgnc:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 10000

  # Ensembl API settings
  ensembl:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 5000

  # HPO API settings
  hpo:
    timeout: 30
    max_retries: 3
    retry_delay: 1.0
    cache_size: 5000

# Output formats
output:
  # Formats to generate
  formats:
    - "excel"    # Comprehensive Excel file
    - "csv"      # CSV for programmatic use
    - "parquet"  # Efficient binary format
    - "bed"      # BED files for genome browsers

  # BED file generation
  bed_files:
    # Generate BED file for included genes
    germline: true
    # Extend gene coordinates by this many base pairs
    padding: 0

  # Intermediate file output for debugging
  intermediate_files:
    # Enable intermediate file output
    enabled: true
    # Output format for intermediate files ("csv", "excel", "parquet")
    format: "excel"
    # Include raw source data
    include_raw_data: true
    # Include standardized data
    include_standardized_data: true
    # Include merged data before scoring
    include_merged_data: true
    # Include scored data before decision logic
    include_scored_data: true
    # Include annotated final data
    include_annotated_data: true
    # Compress output files
    compress: false

  # Structured logging to files
  file_logging:
    # Enable logging to files
    enabled: false
    # Log format ("json", "text")
    format: "text"
    # Include debug logs
    include_debug: true
    # Separate log files by component
    separate_by_component: true
    # Components to log separately (if separate_by_component is true)
    components:
      - "hgnc_client"
      - "ensembl_client"
      - "merger"
      - "annotator"
      - "sources"

# Quality control
quality_control:
  # Remove genes not found in HGNC
  require_hgnc_match: true
  # Remove genes without genomic coordinates
  require_coordinates: true
  # Remove duplicates based on HGNC ID
  remove_duplicates: true
  # Minimum gene size (in base pairs) to include
  min_gene_size: 1000

# Reporting
reporting:
  # Generate summary statistics
  generate_summary: true
  # Include source breakdown in reports
  include_source_breakdown: true
  # Generate plots and visualizations
  generate_plots: false

# Performance settings
performance:
  # Number of parallel requests for batch operations
  max_workers: 4
  # Chunk size for batch processing
  batch_size: 100
  # Enable caching of API responses
  enable_caching: true
  # Cache directory
  cache_dir: ".cache"

# Directory structure for outputs
directory_structure:
  # Base structure for organized outputs
  use_structured_output: true
  # Subdirectories for different analysis stages
  subdirs:
    raw_data: "01_raw_data"
    standardized_data: "02_standardized_data"
    merged_data: "03_merged_data"
    scored_data: "04_scored_data"
    annotated_data: "05_annotated_data"
    final_output: "06_final_output"
    logs: "logs"
    cache: "cache"
  # Timestamp format for run-specific directories
  timestamp_format: "%Y%m%d_%H%M%S"

# Scrapers configuration for commercial panels
scrapers:
  # Myriad myRisk panel
  myriad_myrisk:
    enabled: true
    url: "https://myriad.com/gene-table/"
    parser_module: "parse_myriad"
    parser_class: "MyriadParser"
    output_path: "data/scraped/myriad_myrisk.json"
  
  # Blueprint Genetics panels (multiple URLs)
  blueprint_genetics:
    enabled: true
    url: "https://blueprintgenetics.com/tests/panels/hereditary-cancer/"
    subpanel_urls:
      - "https://blueprintgenetics.com/tests/panels/hematology/comprehensive-hematology-and-hereditary-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/comprehensive-hereditary-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-breast-and-gynecological-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-breast-cancer-high-risk-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-cancer-high-risk-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-colorectal-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-endocrine-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-gastrointestinal-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hematology/hereditary-leukemia-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-lung-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/hereditary-melanoma-and-skin-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-pancreatic-cancer-core-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-pancreatic-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-paraganglioma-pheochromocytoma-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-pediatric-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/hereditary-cancer/hereditary-renal-cancer-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/neurofibromatosis-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/tuberous-sclerosis-panel/"
      - "https://blueprintgenetics.com/tests/panels/dermatology/xeroderma-pigmentosum-panel/"
    parser_module: "parse_blueprint"
    parser_class: "BlueprintParser"
    output_path: "data/scraped/blueprint_genetics.json"
  
  # Centogene panels
  centogene:
    enabled: true
    url: "https://www.centoportal.com/order/new/products/analysis-method?queryType=TEST&query=Solid%20tumor"
    parser_module: "parse_centogene"
    parser_class: "CentogeneParser"
    output_path: "data/scraped/centogene.json"
  
  # Fulgent Genetics
  fulgent_genetics:
    enabled: true
    url: "https://www.fulgentgenetics.com/comprehensivecancer-full"
    parser_module: "parse_fulgent"
    parser_class: "FulgentParser"
    output_path: "data/scraped/fulgent_genetics.json"
  
  # CEGAT
  cegat:
    enabled: true
    url: "https://www.cegat.com/diagnostics/diagnostic-panels/tumor-syndromes/"
    parser_module: "parse_cegat"
    parser_class: "CegatParser"
    output_path: "data/scraped/cegat.json"
  
  # Invitae
  invitae_comprehensive:
    enabled: true
    url: "https://www.invitae.com/en/providers/test-catalog/test-01101"
    parser_module: "parse_invitae"
    parser_class: "InvitaeParser"
    output_path: "data/scraped/invitae_comprehensive.json"
  
  # MGZ
  mgz:
    enabled: true
    url: "https://www.mgz-muenchen.de/gen-panels/panel/erbliche-tumorerkrankungen-umfassende-diagnostik.html"
    parser_module: "parse_mgz"
    parser_class: "MgzParser"
    output_path: "data/scraped/mgz.json"
  
  # University of Chicago
  uchicago:
    enabled: true
    url: "https://dnatesting.uchicago.edu/tests/comprehensive-hereditary-cancer-panel"
    parser_module: "parse_uchicago"
    parser_class: "UChicagoParser"
    output_path: "data/scraped/uchicago.json"
  
  # Prevention Genetics
  prevention_genetics:
    enabled: true
    url: "https://www.preventiongenetics.com/testInfo?val=Cancer-Panel"
    parser_module: "parse_prevention"
    parser_class: "PreventionParser"
    output_path: "data/scraped/prevention_genetics.json"
  
  # GeneDx
  genedx_comprehensive:
    enabled: true
    url: "https://www.genedx.com/tests/detail/oncogenedx-custom-panel-871"
    parser_module: "parse_genedx"
    parser_class: "GenedxParser"
    output_path: "data/scraped/genedx_comprehensive.json"
  
  # ARUP Laboratories
  arup:
    enabled: true
    url: "https://arupconsult.com/ati/hereditary-cancer-panel"
    parser_module: "parse_arup"
    parser_class: "ArupParser"
    output_path: "data/scraped/arup.json"
  
  # CGL (Cancer Genetics Lab)
  cgl:
    enabled: true
    url: "http://cancergeneticslab.ca/genes/hereditary-cancer-panel/"
    parser_module: "parse_cgl"
    parser_class: "CglParser"
    output_path: "data/scraped/cgl.json"
  
  # NeoGenomics
  neogenomics:
    enabled: true
    url: "https://neogenomics.com/test-menu/full-comprehensive-cancer-panel-germline"
    parser_module: "parse_neogenomics"
    parser_class: "NeogenomicsParser"
    output_path: "data/scraped/neogenomics.json"
  
  # Natera
  natera:
    enabled: true
    url: "https://www.natera.com/oncology/empower-hereditary-cancer-test/clinicians/"
    parser_module: "parse_natera"
    parser_class: "NateraParser"
    output_path: "data/scraped/natera.json"